Setup GH Actions
jpadilla/pyjwt pull request #499
Opened 2020-06-19 14:51 UTC by jpadilla

2020-08-13 09:23 UTC, auvipy commented on .github/workflows/main.yml
> +        python-version: ["3.5", "3.6", "3.7", "3.8"]
as python 3.5 will be EOL in October 2020, we can drop it now

2020-08-13 09:38 UTC, auvipy commented on setup.cfg
> +    pytest>=4.3.0,<5.0.0
pytest 6 is latest

2020-08-19 02:55 UTC, auvipy requested changes

2020-08-19 02:55 UTC, auvipy commented on docs/conf.py
> +# -*- coding: utf-8 -*-
isn;t python 2 support dropped?

2020-08-19 02:55 UTC, auvipy commented on tox.ini
> +    2.7: py27
python 2.7 is EOL

2020-08-19 02:55 UTC, auvipy commented on docs/conf.py
> +        u"PyJWT Documentation",
wy u?

2020-08-19 11:45 UTC, jpadilla commented on docs/conf.py
> +        u"PyJWT Documentation",
woops

2020-08-19 14:37 UTC, auvipy approved these changes

2020-08-19 14:38 UTC, merged

2020-08-19 14:42 UTC, jpadilla commented
thanks @auvipy I have to cleanup badges and remove integrations next.

2020-08-19 14:43 UTC, auvipy commented
ok great!