Update return type for jwt.encode
jpadilla/pyjwt pull request #521
Opened 2020-10-01 19:19 UTC by moomoolive

It seems to me that the return type for the encode method is actually 'bytes' type and not 'str'. While this doesn't make a huge difference working with python code, it gave me some issues yesterday when sending JWT tokens between a Python (flask) REST API and Javascript (Vue) frontend.

2020-10-12 06:06 UTC, auvipy approved these changes

2020-10-12 06:08 UTC, auvipy requested changes
can you share what errors you are facing?

2020-10-12 13:33 UTC, moomoolive commented
It was honestly pretty simple, since the 'jwt.encode' method outputs a bytes object and not a string, I ended up sending something that looked like this to my front end application:

b'<the jwt token>'

instead of just the token itself. 

The problem arose when I tried to use the token for authorization (decode it), where it would throw an 'invalid header padding warning' because I was sending the bytes object of the token, instead of the string of the token itself.

Hope that makes sense.

2020-10-15 08:19 UTC, auvipy approved these changes

2020-10-15 08:20 UTC, merged

2020-10-23 15:53 UTC, tlinhart commented
@moomoolive @auvipy I think this PR should be reverted as it seems that https://github.com/jpadilla/pyjwt/pull/513 actually made `encode` return a string. `PyJWT.encode()` uses its base class' `encode` method which returns string, see https://github.com/jpadilla/pyjwt/blob/96ec8639a544c70f4e427942f109dfe59f0d848c/jwt/api_jws.py#L130.

2020-10-23 18:46 UTC, moomoolive commented
@tlinhart although the line of code you referenced above should solve the problem, it doesn't seem to work when I try it in my terminal. (BTW I'm using the latest distribution of library 1.7.1)

![image](https://user-images.githubusercontent.com/63522515/97041950-8c826700-152d-11eb-9d1c-cb37d3a589a5.png)

It only becomes a string when I decode the token with ASCII.

![image](https://user-images.githubusercontent.com/63522515/97042099-c5224080-152d-11eb-9506-68a0688b0c00.png)

2020-10-23 18:58 UTC, tlinhart commented
Well, in 1.7.1 it returns bytes, but not in master. The current (master) version returns str and thus this PR (which was merged into master 8 days ago) should be reverted.

2021-01-15 06:14 UTC, rayluo commented
@tlinhart was right on this:

> Well, in 1.7.1 it returns bytes, but not in master. The current (master) version returns str and thus this PR (which was merged into master 8 days ago) should be reverted.

And, to document my investigation findings here: even though this PR was mentioned in the v2.0.0 release notes and changelogs, but [that line was indeed reverted subsequently](https://github.com/jpadilla/pyjwt/commit/4265a4168cfc07436e14a16cb9535c8078115020). In other words, `encode(...)` returns a string, not bytes.