Add support for multiple issuers
jpadilla/pyjwt pull request #627
Opened 2021-03-09 18:13 UTC by patrick91

Closes #433

2021-03-18 22:28 UTC, jpadilla requested changes

2021-03-18 22:28 UTC, jpadilla commented on jwt/api_jwt.py
> +        if isinstance(issuer, str):
do we also need to guard against other invalid values for `issuer`?

see https://github.com/jpadilla/pyjwt/blob/master/jwt/api_jwt.py#L128-L129

2021-03-19 01:10 UTC, dimaqq commented on tests/test_api_jwt.py
> +        jwt.decode(token, "secret", issuer=[issuer, "urn:bar"], algorithms=["HS256"])
The spec insists on issuers being HTTPS URLs:
https://openid.net/specs/openid-connect-core-1_0.html#Terminology

```suggestion
        jwt.decode(token, "secret", issuer=[issuer, "https://other.test"], algorithms=["HS256"])
```

2021-03-19 01:11 UTC, dimaqq commented on tests/test_api_jwt.py
> +        jwt.decode(token, "secret", issuer=[issuer, "urn:bar"], algorithms=["HS256"])
(arguably `pyjwt` could be used in other contexts, not just oidc)

2021-11-22 19:47 UTC, peterfarrell commented
I'm interested in this feature.

2022-05-31 02:12 UTC, closed without merging

2022-07-01 08:16 UTC, ChegeBryan commented
> I'm interested in this feature.

That makes two of us.

2022-07-01 08:17 UTC, ChegeBryan commented
@jpadilla is support for multiple issuers coming soon?

2022-07-09 01:36 UTC, jpadilla commented
there were some unresolved comments on this pull request, I'd gladly review again another.