Don't raise error when algorithm is not support
jpadilla/pyjwt pull request #746
Opened 2022-04-07 06:03 UTC by oddbeck

Instead of raising an error for not supported algorithm we log the warning, and continue with other algorithms/keys

2022-04-07 17:54 UTC, auvipy requested changes
check the build failures please

2022-04-07 20:23 UTC, oddbeck commented
> 

I'm off for the easter holydays without a computer, will look into it in a week.

2022-04-11 15:17 UTC, akx requested changes

2022-04-11 15:17 UTC, akx commented on jwt/api_jwk.py
> +            self.key = self.Algorithm.from_jwk(self._jwk_data)
I think this might have security implications, as users of this class likely expect the algorithm in the JWK data to be valid.

2022-05-28 09:28 UTC, DaGuich commented
Should be fixed with https://github.com/jpadilla/pyjwt/pull/762 
Sorry, I've seen the PR too late

2022-08-05 02:13 UTC, closed without merging