Handling 'ImmatureSignatureError' for issued_at time
jpadilla/pyjwt pull request #794
Opened 2022-08-24 17:45 UTC by sriharan16

Handling 'ImmatureSignatureError' for issued_at time when it is a future time epoch.
```
if iat > (now + leeway):
   raise ImmatureSignatureError("The token is not yet valid (iat)")
```

When the `issued_at` time in the payload is greater than the `current time + leeway` then we can call it out as `ImmatureSignatureError` as we do for `(nbf)`

2022-08-26 05:11 UTC, sriharan16 commented
@jpadilla Kindly help here in validating and reviewing this PR.

2022-09-18 14:58 UTC, auvipy requested changes
please rebase

2022-09-22 12:11 UTC, sriharan16 commented
@auvipy I have rebased as mentioned.
Also not sure why requesting your review removed @jpadilla! Kindly verify the changes and also add @jpadilla again as a reviewer

2022-10-14 07:41 UTC, sriharan16 commented
Team(@jpadilla, @auvipy ),

Can you please review this !

2022-10-14 17:28 UTC, auvipy commented
ci triggerred

2022-10-15 07:46 UTC, auvipy approved these changes

2022-10-15 07:47 UTC, merged

2022-10-21 12:52 UTC, auvipy commented
there is a bug report https://github.com/jpadilla/pyjwt/issues/814 , can you verify?

2022-10-22 08:45 UTC, sriharan16 commented
Replied there.