Add classifier for Python 3.11
jpadilla/pyjwt pull request #818
Opened 2022-10-27 07:58 UTC by eseifert

Some tools or services like https://pyreadiness.org/ use classifiers to check for compatibility with a particular Python version. It would be nice to have classifiers for all tested Python versions in `setup.cfg`.

2022-10-28 01:20 UTC, jpadilla requested changes
Thanks, please update CHANGELOG.

2022-10-28 18:10 UTC, eseifert commented
> Thanks, please update CHANGELOG.

Done.

2022-10-29 08:10 UTC, auvipy approved these changes

2022-10-29 13:27 UTC, jpadilla approved these changes

2022-10-29 13:27 UTC, merged