PyJWT async
jpadilla/pyjwt pull request #956
Opened 2024-05-17 22:39 UTC by padrepitufo

I am somewhat new to contributing to a python library, and I am not sure if the code I'm supplying is needed/wanted by/appropriate for this project.  If there is already a suggested way to use PyJWT within an asynchronous context (like FastAPI) I would like guidance.  If something like this could be useful I can add tests or make changes to align the code with the style of the project.

The purpose of this PR is to mitigate blocking code/calls [such as represented in this tutorial](https://auth0.com/blog/build-and-secure-fastapi-server-with-auth0/) (to `get_signing_key_from_jwt`):

```python

class VerifyToken:
    """Does all the token verification using PyJWT"""

    def __init__(self):
        self.config = get_settings()

        # This gets the JWKS from a given URL and does processing so you can
        # use any of the keys available
        jwks_url = f'https://{self.config.auth0_domain}/.well-known/jwks.json'
        self.jwks_client = jwt.PyJWKClient(jwks_url)

        # 👇 new code
    async def verify(self,
                     security_scopes: SecurityScopes,
                     token: Optional[HTTPAuthorizationCredentials] = Depends(HTTPBearer())
                     ):
        if token is None:
            raise UnauthenticatedException

        # This gets the 'kid' from the passed token
        try:
            signing_key = self.jwks_client.get_signing_key_from_jwt(
                token.credentials
            ).key
        except jwt.exceptions.PyJWKClientError as error:
            raise UnauthorizedException(str(error))
        except jwt.exceptions.DecodeError as error:
            raise UnauthorizedException(str(error))

        try:
            payload = jwt.decode(
                token.credentials,
                signing_key,
                algorithms=self.config.auth0_algorithms,
                audience=self.config.auth0_api_audience,
                issuer=self.config.auth0_issuer,
            )
        except Exception as error:
            raise UnauthorizedException(str(error))
    
        return payload
        # 👆 new code
```

Thank you in advance for any guidance/direction you provide.

2024-05-17 23:05 UTC, padrepitufo commented
apologies on the pre-commit failure, it wasn't working on my end for some reason so I pushed with 🤞 . I'll fix that.  And of course, there is no test coverage - but I didn't want to make a deeper investment until I got some feedback.

2024-05-18 00:56 UTC, padrepitufo commented
fixed (but still a lot of tests pending your response @jpadilla )

2024-05-27 13:02 UTC, yossivainshtein commented
I'm not active on the project, I'm only here to say that YES, i'd love to have this change,
This method (`get_signing_key_from_jwt `) is blocking and should be async. 

I was looking for this functionality today and found this PR, would love to see this included.

2024-06-03 21:00 UTC, Omar12e44 commented
xD

2024-08-09 13:37 UTC, Dazix commented
Any update on this? 
@jpadilla

2024-10-11 16:29 UTC, marcstreetergu commented
I could really use this too, I think @padrepitufo  would make changes if/when there was any traction on this PR from @jpadilla

2025-04-26 07:22 UTC, auvipy requested changes
please, fix the merge conflicts and make the CI green for better review

2025-09-01 02:12 UTC, closed without merging