fix test_utils.py not to xfail
jpadilla/pyjwt pull request #987
Opened 2024-09-12 22:25 UTC by pachewise

See https://docs.pytest.org/en/stable/example/parametrize.html#parametrizing-conditional-raising. We should be "passing" the test if the correct action is to raise a ValueError.

2024-09-15 18:31 UTC, auvipy requested changes
thanks for the patch. can you please check the test failures?

2024-09-16 00:11 UTC, pachewise commented
@auvipy the issue is the one we fixed in #986; once we merge that, the tests should pass here. 
<img width="804" alt="image" src="https://github.com/user-attachments/assets/916c951c-df90-4936-9cb5-be130261dace">

2024-09-28 12:17 UTC, jpadilla approved these changes

2024-09-28 17:10 UTC, auvipy approved these changes

2024-09-28 17:10 UTC, merged