Encode EC keys with a fixed bit length
jpadilla/pyjwt pull request #990
Opened 2024-09-26 12:45 UTC by way-dave

Closes #709 and #925

An optional `bit_length` field is added to `utils.bytes_from_int` and `utils.to_base64url_uint`. This is used to encode the EC JWK fields `x`, `y`, and `d` to a fixed byte length.

Prior to this change, the encoded byte length was variable, but the JWK validator required it to be fixed.

2024-09-26 13:02 UTC, JimNero009 approved these changes
🚀

2024-10-06 20:24 UTC, jpadilla approved these changes
thank you! mind updating the changelog?

2024-10-07 20:38 UTC, jpadilla requested changes
there's some tests that are failing

2024-10-10 11:48 UTC, way-dave commented
Thanks! Hopefully those tests will work now. It looked to be a simple typing error.

Changelog updated.

2024-10-13 19:36 UTC, jpadilla approved these changes
awesome, thanks!

2024-10-13 19:36 UTC, merged